//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bramki_Notify.EventLogManagement
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventLogEntryData", Namespace="http://schemas.datacontract.org/2004/07/Roger.Racs.Domain.MainModule.Dto", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bramki_Notify.EventLogManagement.EventLogEntryViewData))]
    public partial class EventLogEntryData : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Nullable<int> AccessCredentialIDField;
        
        private int ActionStatusField;
        
        private System.Nullable<int> AssetIDField;
        
        private System.Nullable<int> CategoryIDField;
        
        private string CommentField;
        
        private System.Nullable<int> ControllerIDField;
        
        private string DetailsField;
        
        private int EventCodeField;
        
        private int EventIDField;
        
        private int EventTagField;
        
        private System.Nullable<int> FunctionField;
        
        private System.Nullable<int> GroupIDField;
        
        private int IDField;
        
        private System.Nullable<int> LocationIDField;
        
        private System.DateTime LoggedOnField;
        
        private System.Nullable<int> NetworkIDField;
        
        private string OptionField;
        
        private System.Nullable<short> OptionTypeField;
        
        private System.Nullable<int> PersonIDField;
        
        private System.Nullable<int> SourceIDField;
        
        private System.Nullable<short> SourceTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AccessCredentialID
        {
            get
            {
                return this.AccessCredentialIDField;
            }
            set
            {
                if ((this.AccessCredentialIDField.Equals(value) != true))
                {
                    this.AccessCredentialIDField = value;
                    this.RaisePropertyChanged("AccessCredentialID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActionStatus
        {
            get
            {
                return this.ActionStatusField;
            }
            set
            {
                if ((this.ActionStatusField.Equals(value) != true))
                {
                    this.ActionStatusField = value;
                    this.RaisePropertyChanged("ActionStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AssetID
        {
            get
            {
                return this.AssetIDField;
            }
            set
            {
                if ((this.AssetIDField.Equals(value) != true))
                {
                    this.AssetIDField = value;
                    this.RaisePropertyChanged("AssetID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CategoryID
        {
            get
            {
                return this.CategoryIDField;
            }
            set
            {
                if ((this.CategoryIDField.Equals(value) != true))
                {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this.CommentField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CommentField, value) != true))
                {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ControllerID
        {
            get
            {
                return this.ControllerIDField;
            }
            set
            {
                if ((this.ControllerIDField.Equals(value) != true))
                {
                    this.ControllerIDField = value;
                    this.RaisePropertyChanged("ControllerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details
        {
            get
            {
                return this.DetailsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DetailsField, value) != true))
                {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventCode
        {
            get
            {
                return this.EventCodeField;
            }
            set
            {
                if ((this.EventCodeField.Equals(value) != true))
                {
                    this.EventCodeField = value;
                    this.RaisePropertyChanged("EventCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventID
        {
            get
            {
                return this.EventIDField;
            }
            set
            {
                if ((this.EventIDField.Equals(value) != true))
                {
                    this.EventIDField = value;
                    this.RaisePropertyChanged("EventID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventTag
        {
            get
            {
                return this.EventTagField;
            }
            set
            {
                if ((this.EventTagField.Equals(value) != true))
                {
                    this.EventTagField = value;
                    this.RaisePropertyChanged("EventTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Function
        {
            get
            {
                return this.FunctionField;
            }
            set
            {
                if ((this.FunctionField.Equals(value) != true))
                {
                    this.FunctionField = value;
                    this.RaisePropertyChanged("Function");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GroupID
        {
            get
            {
                return this.GroupIDField;
            }
            set
            {
                if ((this.GroupIDField.Equals(value) != true))
                {
                    this.GroupIDField = value;
                    this.RaisePropertyChanged("GroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LocationID
        {
            get
            {
                return this.LocationIDField;
            }
            set
            {
                if ((this.LocationIDField.Equals(value) != true))
                {
                    this.LocationIDField = value;
                    this.RaisePropertyChanged("LocationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LoggedOn
        {
            get
            {
                return this.LoggedOnField;
            }
            set
            {
                if ((this.LoggedOnField.Equals(value) != true))
                {
                    this.LoggedOnField = value;
                    this.RaisePropertyChanged("LoggedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NetworkID
        {
            get
            {
                return this.NetworkIDField;
            }
            set
            {
                if ((this.NetworkIDField.Equals(value) != true))
                {
                    this.NetworkIDField = value;
                    this.RaisePropertyChanged("NetworkID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Option
        {
            get
            {
                return this.OptionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OptionField, value) != true))
                {
                    this.OptionField = value;
                    this.RaisePropertyChanged("Option");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> OptionType
        {
            get
            {
                return this.OptionTypeField;
            }
            set
            {
                if ((this.OptionTypeField.Equals(value) != true))
                {
                    this.OptionTypeField = value;
                    this.RaisePropertyChanged("OptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PersonID
        {
            get
            {
                return this.PersonIDField;
            }
            set
            {
                if ((this.PersonIDField.Equals(value) != true))
                {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SourceID
        {
            get
            {
                return this.SourceIDField;
            }
            set
            {
                if ((this.SourceIDField.Equals(value) != true))
                {
                    this.SourceIDField = value;
                    this.RaisePropertyChanged("SourceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> SourceType
        {
            get
            {
                return this.SourceTypeField;
            }
            set
            {
                if ((this.SourceTypeField.Equals(value) != true))
                {
                    this.SourceTypeField = value;
                    this.RaisePropertyChanged("SourceType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventLogEntryViewData", Namespace="http://schemas.datacontract.org/2004/07/Roger.Racs.Domain.MainModule.Dto", IsReference=true)]
    public partial class EventLogEntryViewData : Bramki_Notify.EventLogManagement.EventLogEntryData
    {
        
        private string AssetNameField;
        
        private int BackColorField;
        
        private string ControllerNameField;
        
        private string CredentialNameField;
        
        private string EventNameField;
        
        private int ForeColorField;
        
        private string GroupNameField;
        
        private string LocationNameField;
        
        private string NetworkNameField;
        
        private string OptionNameField;
        
        private string PersonNameField;
        
        private string SourceNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssetName
        {
            get
            {
                return this.AssetNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AssetNameField, value) != true))
                {
                    this.AssetNameField = value;
                    this.RaisePropertyChanged("AssetName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BackColor
        {
            get
            {
                return this.BackColorField;
            }
            set
            {
                if ((this.BackColorField.Equals(value) != true))
                {
                    this.BackColorField = value;
                    this.RaisePropertyChanged("BackColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ControllerName
        {
            get
            {
                return this.ControllerNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ControllerNameField, value) != true))
                {
                    this.ControllerNameField = value;
                    this.RaisePropertyChanged("ControllerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CredentialName
        {
            get
            {
                return this.CredentialNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CredentialNameField, value) != true))
                {
                    this.CredentialNameField = value;
                    this.RaisePropertyChanged("CredentialName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventName
        {
            get
            {
                return this.EventNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EventNameField, value) != true))
                {
                    this.EventNameField = value;
                    this.RaisePropertyChanged("EventName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ForeColor
        {
            get
            {
                return this.ForeColorField;
            }
            set
            {
                if ((this.ForeColorField.Equals(value) != true))
                {
                    this.ForeColorField = value;
                    this.RaisePropertyChanged("ForeColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName
        {
            get
            {
                return this.GroupNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true))
                {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationName
        {
            get
            {
                return this.LocationNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LocationNameField, value) != true))
                {
                    this.LocationNameField = value;
                    this.RaisePropertyChanged("LocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NetworkName
        {
            get
            {
                return this.NetworkNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NetworkNameField, value) != true))
                {
                    this.NetworkNameField = value;
                    this.RaisePropertyChanged("NetworkName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OptionName
        {
            get
            {
                return this.OptionNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OptionNameField, value) != true))
                {
                    this.OptionNameField = value;
                    this.RaisePropertyChanged("OptionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonName
        {
            get
            {
                return this.PersonNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PersonNameField, value) != true))
                {
                    this.PersonNameField = value;
                    this.RaisePropertyChanged("PersonName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceName
        {
            get
            {
                return this.SourceNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SourceNameField, value) != true))
                {
                    this.SourceNameField = value;
                    this.RaisePropertyChanged("SourceName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventFilterData", Namespace="http://schemas.datacontract.org/2004/07/Roger.Racs.Domain.MainModule.Dto", IsReference=true)]
    public partial class EventFilterData : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string AccessZonesField;
        
        private string AlarmZonesField;
        
        private string AssetsField;
        
        private string AutomationPointsField;
        
        private string CategoriesField;
        
        private string ControllersField;
        
        private string DetailsField;
        
        private string DoorsField;
        
        private string EventsField;
        
        private string FunctionKeysField;
        
        private string GroupsField;
        
        private int IDField;
        
        private string InputsField;
        
        private bool IsSystemFilterField;
        
        private int LimitResultField;
        
        private string LocationsField;
        
        private string NameField;
        
        private string NetworksField;
        
        private string PersonsField;
        
        private string PointSourcesField;
        
        private string PointsField;
        
        private string SeveritiesField;
        
        private string SourcesField;
        
        private System.Nullable<System.DateTime> TimeRangeEndField;
        
        private System.Nullable<System.DateTime> TimeRangeStartField;
        
        private byte TimeRangeTypeField;
        
        private string UsersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessZones
        {
            get
            {
                return this.AccessZonesField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AccessZonesField, value) != true))
                {
                    this.AccessZonesField = value;
                    this.RaisePropertyChanged("AccessZones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlarmZones
        {
            get
            {
                return this.AlarmZonesField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AlarmZonesField, value) != true))
                {
                    this.AlarmZonesField = value;
                    this.RaisePropertyChanged("AlarmZones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Assets
        {
            get
            {
                return this.AssetsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AssetsField, value) != true))
                {
                    this.AssetsField = value;
                    this.RaisePropertyChanged("Assets");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AutomationPoints
        {
            get
            {
                return this.AutomationPointsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AutomationPointsField, value) != true))
                {
                    this.AutomationPointsField = value;
                    this.RaisePropertyChanged("AutomationPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Categories
        {
            get
            {
                return this.CategoriesField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CategoriesField, value) != true))
                {
                    this.CategoriesField = value;
                    this.RaisePropertyChanged("Categories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Controllers
        {
            get
            {
                return this.ControllersField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ControllersField, value) != true))
                {
                    this.ControllersField = value;
                    this.RaisePropertyChanged("Controllers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details
        {
            get
            {
                return this.DetailsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DetailsField, value) != true))
                {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Doors
        {
            get
            {
                return this.DoorsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DoorsField, value) != true))
                {
                    this.DoorsField = value;
                    this.RaisePropertyChanged("Doors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Events
        {
            get
            {
                return this.EventsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EventsField, value) != true))
                {
                    this.EventsField = value;
                    this.RaisePropertyChanged("Events");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FunctionKeys
        {
            get
            {
                return this.FunctionKeysField;
            }
            set
            {
                if ((object.ReferenceEquals(this.FunctionKeysField, value) != true))
                {
                    this.FunctionKeysField = value;
                    this.RaisePropertyChanged("FunctionKeys");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Groups
        {
            get
            {
                return this.GroupsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.GroupsField, value) != true))
                {
                    this.GroupsField = value;
                    this.RaisePropertyChanged("Groups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Inputs
        {
            get
            {
                return this.InputsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.InputsField, value) != true))
                {
                    this.InputsField = value;
                    this.RaisePropertyChanged("Inputs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSystemFilter
        {
            get
            {
                return this.IsSystemFilterField;
            }
            set
            {
                if ((this.IsSystemFilterField.Equals(value) != true))
                {
                    this.IsSystemFilterField = value;
                    this.RaisePropertyChanged("IsSystemFilter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LimitResult
        {
            get
            {
                return this.LimitResultField;
            }
            set
            {
                if ((this.LimitResultField.Equals(value) != true))
                {
                    this.LimitResultField = value;
                    this.RaisePropertyChanged("LimitResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Locations
        {
            get
            {
                return this.LocationsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LocationsField, value) != true))
                {
                    this.LocationsField = value;
                    this.RaisePropertyChanged("Locations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NameField, value) != true))
                {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Networks
        {
            get
            {
                return this.NetworksField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NetworksField, value) != true))
                {
                    this.NetworksField = value;
                    this.RaisePropertyChanged("Networks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Persons
        {
            get
            {
                return this.PersonsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PersonsField, value) != true))
                {
                    this.PersonsField = value;
                    this.RaisePropertyChanged("Persons");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PointSources
        {
            get
            {
                return this.PointSourcesField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PointSourcesField, value) != true))
                {
                    this.PointSourcesField = value;
                    this.RaisePropertyChanged("PointSources");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Points
        {
            get
            {
                return this.PointsField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PointsField, value) != true))
                {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Severities
        {
            get
            {
                return this.SeveritiesField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SeveritiesField, value) != true))
                {
                    this.SeveritiesField = value;
                    this.RaisePropertyChanged("Severities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sources
        {
            get
            {
                return this.SourcesField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SourcesField, value) != true))
                {
                    this.SourcesField = value;
                    this.RaisePropertyChanged("Sources");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TimeRangeEnd
        {
            get
            {
                return this.TimeRangeEndField;
            }
            set
            {
                if ((this.TimeRangeEndField.Equals(value) != true))
                {
                    this.TimeRangeEndField = value;
                    this.RaisePropertyChanged("TimeRangeEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TimeRangeStart
        {
            get
            {
                return this.TimeRangeStartField;
            }
            set
            {
                if ((this.TimeRangeStartField.Equals(value) != true))
                {
                    this.TimeRangeStartField = value;
                    this.RaisePropertyChanged("TimeRangeStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte TimeRangeType
        {
            get
            {
                return this.TimeRangeTypeField;
            }
            set
            {
                if ((this.TimeRangeTypeField.Equals(value) != true))
                {
                    this.TimeRangeTypeField = value;
                    this.RaisePropertyChanged("TimeRangeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Users
        {
            get
            {
                return this.UsersField;
            }
            set
            {
                if ((object.ReferenceEquals(this.UsersField, value) != true))
                {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventData", Namespace="http://schemas.datacontract.org/2004/07/Roger.Racs.Domain.MainModule.Dto", IsReference=true)]
    public partial class EventData : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private bool AlarmField;
        
        private System.Nullable<int> BackColorField;
        
        private int CodeField;
        
        private System.Nullable<int> DefaultCategoryIDField;
        
        private string DescriptionField;
        
        private System.Nullable<int> FontColorField;
        
        private string FontNameField;
        
        private System.Nullable<float> FontSizeField;
        
        private System.Nullable<int> FontStyleField;
        
        private System.Nullable<short> LocationTypeField;
        
        private string NameField;
        
        private byte SeverityField;
        
        private bool SoundField;
        
        private System.Nullable<short> SourceTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Alarm
        {
            get
            {
                return this.AlarmField;
            }
            set
            {
                if ((this.AlarmField.Equals(value) != true))
                {
                    this.AlarmField = value;
                    this.RaisePropertyChanged("Alarm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BackColor
        {
            get
            {
                return this.BackColorField;
            }
            set
            {
                if ((this.BackColorField.Equals(value) != true))
                {
                    this.BackColorField = value;
                    this.RaisePropertyChanged("BackColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                if ((this.CodeField.Equals(value) != true))
                {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DefaultCategoryID
        {
            get
            {
                return this.DefaultCategoryIDField;
            }
            set
            {
                if ((this.DefaultCategoryIDField.Equals(value) != true))
                {
                    this.DefaultCategoryIDField = value;
                    this.RaisePropertyChanged("DefaultCategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true))
                {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FontColor
        {
            get
            {
                return this.FontColorField;
            }
            set
            {
                if ((this.FontColorField.Equals(value) != true))
                {
                    this.FontColorField = value;
                    this.RaisePropertyChanged("FontColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FontName
        {
            get
            {
                return this.FontNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.FontNameField, value) != true))
                {
                    this.FontNameField = value;
                    this.RaisePropertyChanged("FontName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> FontSize
        {
            get
            {
                return this.FontSizeField;
            }
            set
            {
                if ((this.FontSizeField.Equals(value) != true))
                {
                    this.FontSizeField = value;
                    this.RaisePropertyChanged("FontSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FontStyle
        {
            get
            {
                return this.FontStyleField;
            }
            set
            {
                if ((this.FontStyleField.Equals(value) != true))
                {
                    this.FontStyleField = value;
                    this.RaisePropertyChanged("FontStyle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> LocationType
        {
            get
            {
                return this.LocationTypeField;
            }
            set
            {
                if ((this.LocationTypeField.Equals(value) != true))
                {
                    this.LocationTypeField = value;
                    this.RaisePropertyChanged("LocationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NameField, value) != true))
                {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Severity
        {
            get
            {
                return this.SeverityField;
            }
            set
            {
                if ((this.SeverityField.Equals(value) != true))
                {
                    this.SeverityField = value;
                    this.RaisePropertyChanged("Severity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Sound
        {
            get
            {
                return this.SoundField;
            }
            set
            {
                if ((this.SoundField.Equals(value) != true))
                {
                    this.SoundField = value;
                    this.RaisePropertyChanged("Sound");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> SourceType
        {
            get
            {
                return this.SourceTypeField;
            }
            set
            {
                if ((this.SourceTypeField.Equals(value) != true))
                {
                    this.SourceTypeField = value;
                    this.RaisePropertyChanged("SourceType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventLogEntryCategoryData", Namespace="http://schemas.datacontract.org/2004/07/Roger.Racs.Domain.MainModule.Dto", IsReference=true)]
    public partial class EventLogEntryCategoryData : Bramki_Notify.EventLogManagement.BaseData
    {
        
        private System.Nullable<int> ColorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Color
        {
            get
            {
                return this.ColorField;
            }
            set
            {
                if ((this.ColorField.Equals(value) != true))
                {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseData", Namespace="http://schemas.datacontract.org/2004/07/Roger.Racs.Domain.MainModule.Dto", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bramki_Notify.EventLogManagement.EventLogEntryCategoryData))]
    public partial class BaseData : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private bool DeletedField;
        
        private string DescriptionField;
        
        private int IDField;
        
        private string NameField;
        
        private System.Nullable<System.DateTime> UpdatedDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                if ((this.DeletedField.Equals(value) != true))
                {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true))
                {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                if ((this.IDField.Equals(value) != true))
                {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NameField, value) != true))
                {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdatedDate
        {
            get
            {
                return this.UpdatedDateField;
            }
            set
            {
                if ((this.UpdatedDateField.Equals(value) != true))
                {
                    this.UpdatedDateField = value;
                    this.RaisePropertyChanged("UpdatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.roger.pl/eventlog", ConfigurationName="Bramki_Notify.EventLogManagement.IEventLogManagementService")]
    public interface IEventLogManagementService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesBetweenDates", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesBetweenDatesRes" +
            "ponse")]
        Bramki_Notify.EventLogManagement.EventLogEntryData[] GetEntriesBetweenDates(System.DateTime startDateTime, System.DateTime endDateTime, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesBetweenDates", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesBetweenDatesRes" +
            "ponse")]
        System.Threading.Tasks.Task<Bramki_Notify.EventLogManagement.EventLogEntryData[]> GetEntriesBetweenDatesAsync(System.DateTime startDateTime, System.DateTime endDateTime, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/TakeEntriesStartingFrom", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/TakeEntriesStartingFromRe" +
            "sponse")]
        Bramki_Notify.EventLogManagement.EventLogEntryData[] TakeEntriesStartingFrom(int entryId, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/TakeEntriesStartingFrom", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/TakeEntriesStartingFromRe" +
            "sponse")]
        System.Threading.Tasks.Task<Bramki_Notify.EventLogManagement.EventLogEntryData[]> TakeEntriesStartingFromAsync(int entryId, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesViewDataBetween" +
            "Dates", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesViewDataBetween" +
            "DatesResponse")]
        Bramki_Notify.EventLogManagement.EventLogEntryViewData[] GetEntriesViewDataBetweenDates(System.DateTime startDateTime, System.DateTime endDateTime, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesViewDataBetween" +
            "Dates", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesViewDataBetween" +
            "DatesResponse")]
        System.Threading.Tasks.Task<Bramki_Notify.EventLogManagement.EventLogEntryViewData[]> GetEntriesViewDataBetweenDatesAsync(System.DateTime startDateTime, System.DateTime endDateTime, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/TakeEntriesViewDataStarti" +
            "ngFrom", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/TakeEntriesViewDataStarti" +
            "ngFromResponse")]
        Bramki_Notify.EventLogManagement.EventLogEntryViewData[] TakeEntriesViewDataStartingFrom(int entryId, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/TakeEntriesViewDataStarti" +
            "ngFrom", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/TakeEntriesViewDataStarti" +
            "ngFromResponse")]
        System.Threading.Tasks.Task<Bramki_Notify.EventLogManagement.EventLogEntryViewData[]> TakeEntriesViewDataStartingFromAsync(int entryId, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntryById", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntryByIdResponse")]
        Bramki_Notify.EventLogManagement.EventLogEntryData GetEntryById(int id, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntryById", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntryByIdResponse")]
        System.Threading.Tasks.Task<Bramki_Notify.EventLogManagement.EventLogEntryData> GetEntryByIdAsync(int id, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesByFilterId", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesByFilterIdRespo" +
            "nse")]
        Bramki_Notify.EventLogManagement.EventLogEntryData[] GetEntriesByFilterId(int filterId, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesByFilterId", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesByFilterIdRespo" +
            "nse")]
        System.Threading.Tasks.Task<Bramki_Notify.EventLogManagement.EventLogEntryData[]> GetEntriesByFilterIdAsync(int filterId, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesByFilter", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesByFilterRespons" +
            "e")]
        Bramki_Notify.EventLogManagement.EventLogEntryData[] GetEntriesByFilter(Bramki_Notify.EventLogManagement.EventFilterData filter, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesByFilter", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesByFilterRespons" +
            "e")]
        System.Threading.Tasks.Task<Bramki_Notify.EventLogManagement.EventLogEntryData[]> GetEntriesByFilterAsync(Bramki_Notify.EventLogManagement.EventFilterData filter, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesViewDataByFilte" +
            "rId", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesViewDataByFilte" +
            "rIdResponse")]
        Bramki_Notify.EventLogManagement.EventLogEntryViewData[] GetEntriesViewDataByFilterId(int filterId, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesViewDataByFilte" +
            "rId", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesViewDataByFilte" +
            "rIdResponse")]
        System.Threading.Tasks.Task<Bramki_Notify.EventLogManagement.EventLogEntryViewData[]> GetEntriesViewDataByFilterIdAsync(int filterId, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesViewDataByFilte" +
            "r", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesViewDataByFilte" +
            "rResponse")]
        Bramki_Notify.EventLogManagement.EventLogEntryViewData[] GetEntriesViewDataByFilter(Bramki_Notify.EventLogManagement.EventFilterData filter, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesViewDataByFilte" +
            "r", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesViewDataByFilte" +
            "rResponse")]
        System.Threading.Tasks.Task<Bramki_Notify.EventLogManagement.EventLogEntryViewData[]> GetEntriesViewDataByFilterAsync(Bramki_Notify.EventLogManagement.EventFilterData filter, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/GetAllEvents", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/GetAllEventsResponse")]
        Bramki_Notify.EventLogManagement.EventData[] GetAllEvents(System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/GetAllEvents", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/GetAllEventsResponse")]
        System.Threading.Tasks.Task<Bramki_Notify.EventLogManagement.EventData[]> GetAllEventsAsync(System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/GetAllEventCategories", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/GetAllEventCategoriesResp" +
            "onse")]
        Bramki_Notify.EventLogManagement.EventLogEntryCategoryData[] GetAllEventCategories(System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/GetAllEventCategories", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/GetAllEventCategoriesResp" +
            "onse")]
        System.Threading.Tasks.Task<Bramki_Notify.EventLogManagement.EventLogEntryCategoryData[]> GetAllEventCategoriesAsync(System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/GetAllEventFilters", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/GetAllEventFiltersRespons" +
            "e")]
        Bramki_Notify.EventLogManagement.EventFilterData[] GetAllEventFilters(System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/GetAllEventFilters", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/GetAllEventFiltersRespons" +
            "e")]
        System.Threading.Tasks.Task<Bramki_Notify.EventLogManagement.EventFilterData[]> GetAllEventFiltersAsync(System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/GetLastEntryId", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/GetLastEntryIdResponse")]
        int GetLastEntryId(System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/GetLastEntryId", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/GetLastEntryIdResponse")]
        System.Threading.Tasks.Task<int> GetLastEntryIdAsync(System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesCountBetweenDat" +
            "es", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesCountBetweenDat" +
            "esResponse")]
        int GetEntriesCountBetweenDates(System.DateTime startDateTime, System.DateTime endDateTime, System.Guid sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesCountBetweenDat" +
            "es", ReplyAction="http://www.roger.pl/eventlog/IEventLogManagementService/GetEntriesCountBetweenDat" +
            "esResponse")]
        System.Threading.Tasks.Task<int> GetEntriesCountBetweenDatesAsync(System.DateTime startDateTime, System.DateTime endDateTime, System.Guid sessionToken);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IEventLogManagementServiceChannel : Bramki_Notify.EventLogManagement.IEventLogManagementService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class EventLogManagementServiceClient : System.ServiceModel.ClientBase<Bramki_Notify.EventLogManagement.IEventLogManagementService>, Bramki_Notify.EventLogManagement.IEventLogManagementService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EventLogManagementServiceClient() : 
                base(EventLogManagementServiceClient.GetDefaultBinding(), EventLogManagementServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IEventLogManagementService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EventLogManagementServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(EventLogManagementServiceClient.GetBindingForEndpoint(endpointConfiguration), EventLogManagementServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EventLogManagementServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EventLogManagementServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EventLogManagementServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EventLogManagementServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EventLogManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Bramki_Notify.EventLogManagement.EventLogEntryData[] GetEntriesBetweenDates(System.DateTime startDateTime, System.DateTime endDateTime, System.Guid sessionToken)
        {
            return base.Channel.GetEntriesBetweenDates(startDateTime, endDateTime, sessionToken);
        }
        
        public System.Threading.Tasks.Task<Bramki_Notify.EventLogManagement.EventLogEntryData[]> GetEntriesBetweenDatesAsync(System.DateTime startDateTime, System.DateTime endDateTime, System.Guid sessionToken)
        {
            return base.Channel.GetEntriesBetweenDatesAsync(startDateTime, endDateTime, sessionToken);
        }
        
        public Bramki_Notify.EventLogManagement.EventLogEntryData[] TakeEntriesStartingFrom(int entryId, System.Guid sessionToken)
        {
            return base.Channel.TakeEntriesStartingFrom(entryId, sessionToken);
        }
        
        public System.Threading.Tasks.Task<Bramki_Notify.EventLogManagement.EventLogEntryData[]> TakeEntriesStartingFromAsync(int entryId, System.Guid sessionToken)
        {
            return base.Channel.TakeEntriesStartingFromAsync(entryId, sessionToken);
        }
        
        public Bramki_Notify.EventLogManagement.EventLogEntryViewData[] GetEntriesViewDataBetweenDates(System.DateTime startDateTime, System.DateTime endDateTime, System.Guid sessionToken)
        {
            return base.Channel.GetEntriesViewDataBetweenDates(startDateTime, endDateTime, sessionToken);
        }
        
        public System.Threading.Tasks.Task<Bramki_Notify.EventLogManagement.EventLogEntryViewData[]> GetEntriesViewDataBetweenDatesAsync(System.DateTime startDateTime, System.DateTime endDateTime, System.Guid sessionToken)
        {
            return base.Channel.GetEntriesViewDataBetweenDatesAsync(startDateTime, endDateTime, sessionToken);
        }
        
        public Bramki_Notify.EventLogManagement.EventLogEntryViewData[] TakeEntriesViewDataStartingFrom(int entryId, System.Guid sessionToken)
        {
            return base.Channel.TakeEntriesViewDataStartingFrom(entryId, sessionToken);
        }
        
        public System.Threading.Tasks.Task<Bramki_Notify.EventLogManagement.EventLogEntryViewData[]> TakeEntriesViewDataStartingFromAsync(int entryId, System.Guid sessionToken)
        {
            return base.Channel.TakeEntriesViewDataStartingFromAsync(entryId, sessionToken);
        }
        
        public Bramki_Notify.EventLogManagement.EventLogEntryData GetEntryById(int id, System.Guid sessionToken)
        {
            return base.Channel.GetEntryById(id, sessionToken);
        }
        
        public System.Threading.Tasks.Task<Bramki_Notify.EventLogManagement.EventLogEntryData> GetEntryByIdAsync(int id, System.Guid sessionToken)
        {
            return base.Channel.GetEntryByIdAsync(id, sessionToken);
        }
        
        public Bramki_Notify.EventLogManagement.EventLogEntryData[] GetEntriesByFilterId(int filterId, System.Guid sessionToken)
        {
            return base.Channel.GetEntriesByFilterId(filterId, sessionToken);
        }
        
        public System.Threading.Tasks.Task<Bramki_Notify.EventLogManagement.EventLogEntryData[]> GetEntriesByFilterIdAsync(int filterId, System.Guid sessionToken)
        {
            return base.Channel.GetEntriesByFilterIdAsync(filterId, sessionToken);
        }
        
        public Bramki_Notify.EventLogManagement.EventLogEntryData[] GetEntriesByFilter(Bramki_Notify.EventLogManagement.EventFilterData filter, System.Guid sessionToken)
        {
            return base.Channel.GetEntriesByFilter(filter, sessionToken);
        }
        
        public System.Threading.Tasks.Task<Bramki_Notify.EventLogManagement.EventLogEntryData[]> GetEntriesByFilterAsync(Bramki_Notify.EventLogManagement.EventFilterData filter, System.Guid sessionToken)
        {
            return base.Channel.GetEntriesByFilterAsync(filter, sessionToken);
        }
        
        public Bramki_Notify.EventLogManagement.EventLogEntryViewData[] GetEntriesViewDataByFilterId(int filterId, System.Guid sessionToken)
        {
            return base.Channel.GetEntriesViewDataByFilterId(filterId, sessionToken);
        }
        
        public System.Threading.Tasks.Task<Bramki_Notify.EventLogManagement.EventLogEntryViewData[]> GetEntriesViewDataByFilterIdAsync(int filterId, System.Guid sessionToken)
        {
            return base.Channel.GetEntriesViewDataByFilterIdAsync(filterId, sessionToken);
        }
        
        public Bramki_Notify.EventLogManagement.EventLogEntryViewData[] GetEntriesViewDataByFilter(Bramki_Notify.EventLogManagement.EventFilterData filter, System.Guid sessionToken)
        {
            return base.Channel.GetEntriesViewDataByFilter(filter, sessionToken);
        }
        
        public System.Threading.Tasks.Task<Bramki_Notify.EventLogManagement.EventLogEntryViewData[]> GetEntriesViewDataByFilterAsync(Bramki_Notify.EventLogManagement.EventFilterData filter, System.Guid sessionToken)
        {
            return base.Channel.GetEntriesViewDataByFilterAsync(filter, sessionToken);
        }
        
        public Bramki_Notify.EventLogManagement.EventData[] GetAllEvents(System.Guid sessionToken)
        {
            return base.Channel.GetAllEvents(sessionToken);
        }
        
        public System.Threading.Tasks.Task<Bramki_Notify.EventLogManagement.EventData[]> GetAllEventsAsync(System.Guid sessionToken)
        {
            return base.Channel.GetAllEventsAsync(sessionToken);
        }
        
        public Bramki_Notify.EventLogManagement.EventLogEntryCategoryData[] GetAllEventCategories(System.Guid sessionToken)
        {
            return base.Channel.GetAllEventCategories(sessionToken);
        }
        
        public System.Threading.Tasks.Task<Bramki_Notify.EventLogManagement.EventLogEntryCategoryData[]> GetAllEventCategoriesAsync(System.Guid sessionToken)
        {
            return base.Channel.GetAllEventCategoriesAsync(sessionToken);
        }
        
        public Bramki_Notify.EventLogManagement.EventFilterData[] GetAllEventFilters(System.Guid sessionToken)
        {
            return base.Channel.GetAllEventFilters(sessionToken);
        }
        
        public System.Threading.Tasks.Task<Bramki_Notify.EventLogManagement.EventFilterData[]> GetAllEventFiltersAsync(System.Guid sessionToken)
        {
            return base.Channel.GetAllEventFiltersAsync(sessionToken);
        }
        
        public int GetLastEntryId(System.Guid sessionToken)
        {
            return base.Channel.GetLastEntryId(sessionToken);
        }
        
        public System.Threading.Tasks.Task<int> GetLastEntryIdAsync(System.Guid sessionToken)
        {
            return base.Channel.GetLastEntryIdAsync(sessionToken);
        }
        
        public int GetEntriesCountBetweenDates(System.DateTime startDateTime, System.DateTime endDateTime, System.Guid sessionToken)
        {
            return base.Channel.GetEntriesCountBetweenDates(startDateTime, endDateTime, sessionToken);
        }
        
        public System.Threading.Tasks.Task<int> GetEntriesCountBetweenDatesAsync(System.DateTime startDateTime, System.DateTime endDateTime, System.Guid sessionToken)
        {
            return base.Channel.GetEntriesCountBetweenDatesAsync(startDateTime, endDateTime, sessionToken);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEventLogManagementService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEventLogManagementService))
            {
                return new System.ServiceModel.EndpointAddress("http://127.0.0.1:8892/EventLogManagement");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EventLogManagementServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IEventLogManagementService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EventLogManagementServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IEventLogManagementService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IEventLogManagementService,
        }
    }
}
